### ISSUE TITLE
Issue #0 Checklist

### ISSUE THREAD

**Issue by Kroc** [Kroc/nucomer#1]
Planned release date: October 24th 2019

## Milestone 1
Milestone one represents a "minimum viable product".
Just the ability to browse the menu / articles.

- [x] Pack all articles in an issue
- [x] Produce Menu entries from the articles
- [x] Menu navigation
- [x] Exit article, return to menu

## Milestone 2
The next phase is to begin writing content in earnest and using this experience to implement features that article content may rely upon; i.e. formatting

- [ ] Editorial
- [ ] Instructions
- [ ] Text formatting codes?

## Milestone 3
The third phase is turning the outfit+content into a product

- [ ] Fastloader
- [ ] Replace 3rd-party keyboard routine with own, and--
- [ ] Add joystick navigation
- [ ] Music -- **HELP NEEDED**
- [ ] Add colour-wash to the logo
- [ ] Scroll the logo?
- [x] Custom font?

## Milestone 4
The last phase is the beta-testing / 'last minute' release-preparation:

- [ ] Beta testing with real hardware -- **HELP NEEDED**
- [ ] Release notes
- [ ] Release to Pouet
- [ ] Release to CSDB -- **HELP NEEDED** (I don't have an account there)
- [ ] Release to DemoZoo?
- [ ] Camen Design blog post
- [ ] Reddit? -- /r/c64, /r/retroprogramming, ...?
